# Generated by Django 6.1 on 2026-08-19 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('call', 'Ligação'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('meeting', 'Reunião')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='accounts.customer')),
            ],
        ),
    ]
